### ISSUE TITLE
Consider and provide detailed analysis on more than 3 forms of Software Development Methodologies

### ISSUE THREAD

**Issue by huanhuiying** [huanhuiying/DevOps_Oct2021_Team-5#14]

**Comment by huanhuiying** [comment]
Closing issue once this is approved as we have done this in Sprint 1 in Google Docs, with this link: https://docs.google.com/document/d/1_sHOaZ8tsnoGUMHChkj-Xi9k98BbkSDwiSJCe6PYKBw/edit?usp=sharing

**Comment by meganpng** [comment]
Closing approved
