### ISSUE TITLE
Consider and Provide Detailed Analysis on AGILE

### ISSUE THREAD

**Issue by meganpng** [huanhuiying/DevOps_Oct2021_Team-5#16]

**Comment by huanhuiying** [comment]
Closing issue once this is approved as we have done this in Sprint 1 in Google Docs, with this link: https://docs.google.com/document/d/1_sHOaZ8tsnoGUMHChkj-Xi9k98BbkSDwiSJCe6PYKBw/edit?usp=sharing

**Comment by meganpng** [comment]
Approved & closing
