### ISSUE TITLE
US17 - As a user, I want to be able to leave the main menu at any point during the 16 rounds.

### ISSUE THREAD

**Issue by claris0911** [huanhuiying/DevOps_Oct2021_Team-5#24]

**Comment by meganpng** [comment]
I propose to change the name of the user story to 'US17- As a user, I want to be able to select the "Exit" option the game menu at any point during the 16 rounds so I can go back to the main menu.' This is to make the user story clearer to allow for accurate development.

**Comment by claris0911** [comment]
Approve changes :))

**Comment by meganpng** [comment]
Moved to Done as this issue is completed

**Comment by meganpng** [comment]
Made changes to user story name according to approval
